file(GLOB_RECURSE TEST_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
add_executable(mlibc_tests ${TEST_SOURCES})
target_include_directories(mlibc_tests PRIVATE include)
target_link_libraries(mlibc_tests PRIVATE mlibc_entry "${CMAKE_BINARY_DIR}/libc.so")
add_dependencies(mlibc_tests mlibc)
target_link_options(mlibc_tests PRIVATE -nostdlib -fpie)
target_include_directories(mlibc_tests PRIVATE "${CMAKE_BINARY_DIR}/include")

add_executable(mlibc_tests_static ${TEST_SOURCES})
target_include_directories(mlibc_tests PRIVATE include)
target_link_libraries(mlibc_tests_static PRIVATE mlibc_static mlibc_entry)
target_link_options(mlibc_tests_static PRIVATE -nostdlib -fpie)
target_include_directories(mlibc_tests_static PRIVATE "${CMAKE_BINARY_DIR}/include")